### ISSUE TITLE
Docs link is broken

### ISSUE THREAD

**Issue by FatGrizzly** [creatort/blastoff-framework#1]
https://ihavea.questionable.link/xD3Qp8

**Comment by creatort** [comment]
Yeah, it's not actively developed on any more so the domain just died.
If you want to know anything let me know.

**Comment by FatGrizzly** [comment]
Hmm, replace it with this?
https://app.gitbook.com/@blastoff/s/blastoff-js-framework

**Comment by creatort** [comment]
Yeah, I could I guess

**Comment by creatort** [comment]
Fixed that then.
